### ISSUE TITLE
Create Python Application Action

### ISSUE THREAD

**Issue by seanbsu** [cs481-ekh/s24-meshers#29] opened 2024-02-06 17:36 UTC
references #20 

- [ ] use the github action template for a python application
- [ ] should be configured to run tests on a pull request and merge
- [ ] should use pyUnit to run the tests
- [ ] test with a pull request and find the output

**Comment by paulvxx** [comment] 2024-02-09 05:56
Note:  Running pytest is acceptable too.  It effectively does the same thing.

**Comment by paulvxx** [comment] 2024-02-10 00:45
Issue is a duplicate of #31, #32, and #26 combined  [each of the criteria touches on one of these other three tasks].

(from prior work)

[t:10]

**Closed by paulvxx** 2024-02-10 00:45 UTC
Labels: task
